# Generated by Django 2.2 on 2021-02-20 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0002_auto_20210220_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
