# Generated by Django 3.1.7 on 2021-03-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0002_auto_20210310_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='item_message',
            field=models.ManyToManyField(related_name='item_message', to='exchange_app.Item'),
        ),
    ]
