# Generated by Django 3.1.7 on 2021-03-30 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0004_remove_message_item_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='item_message',
            field=models.ManyToManyField(related_name='item_message', to='exchange_app.Item'),
        ),
    ]
