# Generated by Django 2.2 on 2021-02-21 23:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='inquiry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='exchange_app.Item'),
        ),
    ]
