# Generated by Django 2.2 on 2021-02-21 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0005_message_inquiry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='inquiry',
            new_name='item',
        ),
    ]
