# Generated by Django 2.2 on 2021-02-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0006_auto_20210221_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='item',
        ),
        migrations.AddField(
            model_name='message',
            name='inquery',
            field=models.ManyToManyField(related_name='item_message', to='exchange_app.Item'),
        ),
    ]
