# Generated by Django 2.2 on 2021-02-22 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0007_auto_20210222_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='inquery',
            new_name='inquiry',
        ),
    ]
