# Generated by Django 2.2 on 2021-02-22 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0008_auto_20210222_0110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='inquiry',
        ),
        migrations.AddField(
            model_name='message',
            name='inquiry',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='exchange_app.Item'),
            preserve_default=False,
        ),
    ]
