# Generated by Django 2.2 on 2021-02-22 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0009_auto_20210222_0123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='inquiry',
        ),
        migrations.AddField(
            model_name='message',
            name='inquiry',
            field=models.ManyToManyField(related_name='item_message', to='exchange_app.Item'),
        ),
    ]
