# Generated by Django 2.2 on 2021-02-22 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0010_auto_20210222_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='inquirer',
            field=models.ManyToManyField(related_name='inquirer', to='exchange_app.User'),
        ),
        migrations.AlterField(
            model_name='item',
            name='buyer',
            field=models.ManyToManyField(related_name='buyer', to='exchange_app.User'),
        ),
        migrations.AlterField(
            model_name='item',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='exchange_app.User'),
        ),
        migrations.AlterField(
            model_name='message',
            name='inquiry',
            field=models.ManyToManyField(related_name='inquiry', to='exchange_app.Item'),
        ),
        migrations.AlterField(
            model_name='message',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='exchange_app.User'),
        ),
    ]
