# Generated by Django 2.2 on 2021-02-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0011_auto_20210222_0430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='message',
            name='inquirer',
        ),
        migrations.RemoveField(
            model_name='message',
            name='inquiry',
        ),
        migrations.AddField(
            model_name='item',
            name='saved_item',
            field=models.ManyToManyField(related_name='saved_item', to='exchange_app.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='item_message',
            field=models.ManyToManyField(related_name='item_message', to='exchange_app.Item'),
        ),
        migrations.AddField(
            model_name='message',
            name='sent_message',
            field=models.ManyToManyField(related_name='sent_message', to='exchange_app.User'),
        ),
    ]
