# Generated by Django 2.2 on 2021-02-22 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0013_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
